### ISSUE TITLE
Dataset detail view

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#349]

**Comment by ollehints** [comment]
List of parameters can now be read from solr index, for instance, for dataset_id=11:
"parameter_list":["delta13C [‰]; delta18O [‰]; Mean Amplitude; Mean Area"],
"parameter_index_list":["delta13C_permil; delta18O_permil; Mean_Amplitude; Mean_Area"]
They are ordered by same values, the first values are more appropriate for displaying in table header.
They could be shown as a list also in the general info table. Or even as a set of chips, which can be used to set visibility of columns in results table.

**Comment by Erikdzo** [comment]
Parameters are added to the analyses table in dataset view, but there are cases where a parameter is not set in the dataset. This causes the table to show nothing when sorting on that field , because the query responds with "Error sort param field can't be found". 

You can see this in [dataset/1](https://ema-dev.geoloogia.info/dataset/1/) on parameters **delta13Corg** and **delta15N**.

**Comment by enmust** [comment]
Closing this because dataset view is ok and the parameter problem #370  is open in another issue and it affects also other views
